version: '3'
services:
  nodejs-server:
    build:
      context: ./api
    image: warzinhuw/topicos-especiais:nodejs-server
    ports:
      - "3080:3080"
    volumes:
       - ./api:/usr/src/app/api
       - /usr/src/app/api/node_modules
  vue-ui:
    build:
      context: ./my-app
    image: warzinhuw/topicos-especiais:vue-ui
    ports:
      - "8080:8080"
    volumes:
       - ./my-app:/usr/src/app/my-app
       - /usr/src/app/my-app/node_modules
